use_frameworks!

target 'SYCustomCamera_Example' do
  pod 'SYCustomCamera', :path => '../'

  target 'SYCustomCamera_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
